services:
  build_triedb:
    image: monad-execution-builder:latest
    command: monad_mpt --storage /monad/triedb/test.db --create
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  build_python:
    build:
      context: ${FLEXNET_IMAGE_ROOT}/python
      dockerfile: ${FLEXNET_IMAGE_ROOT}/python/Dockerfile
    image: monad-python:latest

  build_genesis:
    image: monad-execution-builder:latest
    command: monad --chain monad_devnet --db /monad/triedb/test.db --block_db /monad/ledger --nblocks 0 --genesis /monad/config/genesis.json --log_level ERROR
    depends_on:
      build_triedb:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  monad_execution:
    image: monad-execution-builder:latest
    command: monad --chain monad_devnet --db /monad/triedb/test.db --block_db /monad/ledger --statesync /monad/statesync.sock --log_level ERROR
    depends_on:
      build_triedb:
        condition: service_completed_successfully
      build_genesis:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  monad_node:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${DEVNET_DIR}/Dockerfile
    image: monad-node:latest
    depends_on:
      build_triedb:
        condition: service_completed_successfully
      build_genesis:
        condition: service_completed_successfully
    environment:
      - RUST_LOG=
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"

  monad_rpc:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${RPC_DIR}/Dockerfile
    image: monad-rpc:latest
    depends_on:
      - monad_node
    volumes:
      - ./node:/monad
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    ports:
      - "8080:8080"

  e2e_tester:
    image: monad-python:latest
    volumes:
      - ./e2e_tester:/monad
      - ./data:/data
    depends_on:
      - monad_rpc
    entrypoint: ["bash", "/monad/scripts/run.sh"]

networks:
  default:
    driver: bridge
