[package]
name = "monad-twins-utils"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false


[dependencies]
monad-chain-config = { path = "../../monad-chain-config" }
monad-consensus-state = { path = "../../monad-consensus-state" }
monad-consensus-types = { path = "../../monad-consensus-types" }
monad-crypto = { path = "../../monad-crypto" }
monad-mock-swarm = { path = "../../monad-mock-swarm" }
monad-router-scheduler = { path = "../../monad-router-scheduler" }
monad-state = { path = "../../monad-state" }
monad-testutil = { path = "../../monad-testutil" }
monad-transformer = { path = "../../monad-transformer" }
monad-types = { path = "../../monad-types" }
monad-updaters = { path = "../../monad-updaters" }
monad-validator = { path = "../../monad-validator" }
monad-state-backend = { path = "../../monad-state-backend" }

itertools = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["preserve_order"] }
