[package]
name = "monad-state-backend"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-eth-types = { path = "../monad-eth-types" }
monad-types = { path = "../monad-types" }
serde = { workspace = true, features = ["derive"] }