[package]
name = "monad-p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-executor = { path = "../monad-executor" }
monad-crypto = { path = "../monad-crypto", features = ["libp2p-identity"] }

futures = "0.3"
async-trait = "0.1"

libp2p = { version = "0.51", features = ["macros", "mplex", "noise", "identify", "request-response", "secp256k1"] }
