[package]
name = "monad-testground"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[[bin]]
name = "monad-testground"
bench = false

[dependencies]
monad-bls = { workspace = true }
monad-chain-config = { workspace = true }
monad-consensus-state = { workspace = true }
monad-consensus-types = { workspace = true }
monad-control-panel = { workspace = true }
monad-crypto = { workspace = true }
monad-dataplane = { workspace = true }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { workspace = true }
monad-executor-glue = { workspace = true }
monad-peer-discovery = { workspace = true }
monad-raptorcast = { workspace = true }
monad-secp = { workspace = true }
monad-state = { workspace = true }
monad-state-backend = { workspace = true }
monad-types = { workspace = true }
monad-updaters = { workspace = true, features = ["tokio"] }
monad-validator = { workspace = true }

clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
