[package]
name = "monad-testground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-testground"
bench = false

[dependencies]
monad-bls = { path = "../monad-bls" }
monad-chain-config = { path = "../monad-chain-config" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-control-panel = { path = "../monad-control-panel" }
monad-crypto = { path = "../monad-crypto" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-raptorcast = { path = "../monad-raptorcast" }
monad-secp = { path = "../monad-secp" }
monad-state = { path = "../monad-state" }
monad-state-backend = { path = "../monad-state-backend" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters", features = ["tokio"] }
monad-validator = { path = "../monad-validator" }

clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
