[package]
name = "monad-testground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-testground"
bench = false

[dependencies]
monad-block-sync = { path = "../monad-block-sync" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto", features = ["libp2p-identity"] }
monad-election = { path = "../monad-election" }
monad-executor = { path = "../monad-executor", features = ["tokio"] }
monad-p2p = { path = "../monad-p2p", features = ["tokio"] }
monad-state = { path = "../monad-state" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }

clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
futures-util = { workspace = true }
opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry_api = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
