[package]
name = "monad-updaters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-consensus = { path = "../monad-consensus" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-state-backend = { path = "../monad-state-backend" }
monad-triedb = { path = "../monad-triedb", optional = true }
monad-types = { path = "../monad-types" }

alloy-rlp = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
sorted-vec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "time",
    "sync",
], optional = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ntest = { workspace = true }
