[package]
name = "monad-mock-swarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocksync = { path = "../monad-blocksync" }
monad-chain-config = { path = "../monad-chain-config" }
monad-consensus = { path = "../monad-consensus" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-multi-sig = { path = "../monad-multi-sig" }
monad-router-scheduler = { path = "../monad-router-scheduler" }
monad-state = { path = "../monad-state" }
monad-state-backend = { path = "../monad-state-backend" }
monad-transformer = { path = "../monad-transformer" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters" }
monad-validator = { path = "../monad-validator" }

bytes = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
priority-queue = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-bls = { path = "../monad-bls" }
monad-eth-block-policy = { path = "../monad-eth-block-policy" }
monad-eth-block-validator = { path = "../monad-eth-block-validator" }
monad-eth-ledger = { path = "../monad-eth-ledger" }
monad-eth-testutil = { path = "../monad-eth-testutil" }
monad-secp = { path = "../monad-secp" }
monad-testutil = { path = "../monad-testutil" }

alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
criterion = { workspace = true }
test-case = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bench]]
name = "two_node_benchmark"
harness = false
