[package]
name = "monad-mock-swarm"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
monad-blocksync = { workspace = true }
monad-chain-config = { workspace = true }
monad-consensus = { workspace = true }
monad-consensus-types = { workspace = true }
monad-crypto = { workspace = true }
monad-eth-types = { workspace = true }
monad-executor = { workspace = true }
monad-executor-glue = { workspace = true }
monad-multi-sig = { workspace = true }
monad-router-scheduler = { workspace = true }
monad-state = { workspace = true }
monad-state-backend = { workspace = true }
monad-transformer = { workspace = true }
monad-types = { workspace = true }
monad-updaters = { workspace = true }
monad-validator = { workspace = true }

bytes = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
priority-queue = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-bls = { workspace = true }
monad-eth-block-policy = { workspace = true }
monad-eth-block-validator = { workspace = true }
monad-eth-ledger = { workspace = true }
monad-eth-testutil = { workspace = true }
monad-secp = { workspace = true }
monad-testutil = { workspace = true }

alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
criterion = { workspace = true }
test-case = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bench]]
name = "two_node_benchmark"
harness = false
