[package]
name = "monad-node"
description = "Monad consensus node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-node"
bench = false

[dependencies]
monad-bls = { workspace = true }
monad-chain-config = { workspace = true }
monad-consensus-state = { workspace = true }
monad-consensus-types = { workspace = true }
monad-control-panel = { workspace = true }
monad-crypto = { workspace = true }
monad-eth-block-policy = { workspace = true }
monad-eth-block-validator = { workspace = true }
monad-eth-txpool-executor = { workspace = true }
monad-executor = { workspace = true }
monad-executor-glue = { workspace = true }
monad-keystore = { workspace = true }
monad-ledger = { workspace = true }
monad-node-config = { workspace = true, features = ["crypto"] }
monad-raptorcast = { workspace = true }
monad-router-filter = { workspace = true, optional = true }
monad-secp = { workspace = true }
monad-state = { workspace = true }
monad-statesync = { workspace = true }
monad-triedb-cache = { workspace = true }
monad-triedb-utils = { workspace = true }
monad-types = { workspace = true }
monad-updaters = { workspace = true, features = ["monad-triedb", "tokio"] }
monad-validator = { workspace = true }
monad-wal = { workspace = true }

bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
hex = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["metrics", "grpc-tonic"] }
opentelemetry-semantic-conventions = { workspace = true }
rayon = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
monad-block-persist = { workspace = true }

inotify = { workspace = true }
lru = { workspace = true }

[build-dependencies]
vergen-git2 = { workspace = true }

[features]
full-node = ["monad-router-filter"]
