[package]
name = "monad-node"
description = "Monad consensus node"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[[bin]]
name = "monad-node"
bench = false

[lib]
bench = false

[dependencies]
monad-bls = { path = "../monad-bls" }
monad-consensus-state = { path = "../monad-consensus-state" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-control-panel = { path = "../monad-control-panel" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-block-policy = { path = "../monad-eth-block-policy" }
monad-eth-block-validator = { path = "../monad-eth-block-validator" }
monad-eth-txpool = { path = "../monad-eth-txpool" }
monad-eth-types = { path = "../monad-eth-types" }
monad-executor = { path = "../monad-executor" }
monad-executor-glue = { path = "../monad-executor-glue" }
monad-ipc = { path = "../monad-ipc" }
monad-keystore = { path = "../monad-keystore" }
monad-ledger = { path = "../monad-ledger" }
monad-raptorcast = { path = "../monad-raptorcast" }
monad-router-filter = { path = "../monad-router-filter", optional = true }
monad-secp = { path = "../monad-secp" }
monad-state = { path = "../monad-state" }
monad-statesync = { path = "../monad-statesync" }
monad-triedb-cache = { path = "../monad-triedb-cache" }
monad-triedb-utils = { path = "../monad-triedb-utils" }
monad-types = { path = "../monad-types" }
monad-updaters = { path = "../monad-updaters", features = [
    "monad-triedb",
    "tokio",
] }
monad-validator = { path = "../monad-validator" }
monad-wal = { path = "../monad-wal" }

alloy-primitives = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
futures-util = { workspace = true }
hex = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["metrics"] }
opentelemetry-semantic-conventions = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[features]
full-node = ["monad-router-filter"]
