[package]
name = "monad-multi-sig"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-proto = { path = "../monad-proto" }
monad-types = { path = "../monad-types" }

prost = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-testutil = { path = "../monad-testutil" }

rand = { workspace = true }
rand_chacha = { workspace = true }
test-case = { workspace = true }
