[package]
name = "monad-rpc"
description = "Monad JSON-RPC API server"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[[bin]]
name = "monad-rpc"
bench = false

[dependencies]
monad-archive = { workspace = true }
monad-eth-txpool-ipc = { workspace = true }
monad-eth-txpool-types = { workspace = true }
monad-eth-types = { workspace = true }
monad-ethcall = { workspace = true }
monad-rpc-docs = { workspace = true }
monad-triedb-utils = { workspace = true }
monad-types = { workspace = true }

actix = { workspace = true }
actix-http = { workspace = true }
actix-test = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dashmap = { workspace = true }
env_logger = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
notify = { workspace = true }
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true }
pin-project = { workspace = true }
rayon = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net", "macros", "rt-multi-thread", "fs"] }
tracing = { workspace = true, features = ["log"] }
tracing-actix-web = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
alloy-rpc-client = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
reqwest = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
vergen-git2 = { workspace = true }
