[package]
name = "monad-rpc"
description = "Monad JSON-RPC API server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "monad-rpc"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-archive = { path = "../monad-archive" }
monad-cxx = { path = "../monad-cxx" }
monad-eth-block-policy = { path = "../monad-eth-block-policy" }
monad-eth-types = { path = "../monad-eth-types" }
monad-triedb-utils = { path = "../monad-triedb-utils" }
monad-types = { path = "../monad-types" }
monad-rpc-docs = { path = "./monad-rpc-docs" }

actix = { workspace = true }
actix-http = { workspace = true }
actix-test = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
tokio = { workspace = true, features = ["net", "macros", "rt-multi-thread", "fs"] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
notify = "6.1.1"
pin-project = "1.1.5"
scc = { workspace = true }
schemars = "0.8.21"
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry-otlp = "0.17.0"
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }

[dev-dependencies]
alloy-rpc-client = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
reqwest = { workspace = true }
test-case = { workspace = true }
tempfile = { workspace = true }
