[package]
name = "monad-randomized-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monad-chain-config = { path = "../monad-chain-config" }
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-mock-swarm = { path = "../monad-mock-swarm" }
monad-router-scheduler = { path = "../monad-router-scheduler" }
monad-testutil = { path = "../monad-testutil" }
monad-updaters = { path = "../monad-updaters" }
monad-transformer = { path = "../monad-transformer" }
monad-types = { path = "../monad-types" }
monad-validator = { path = "../monad-validator" }
monad-state-backend = { path = "../monad-state-backend" }

inventory = { workspace = true }
simple-xml-builder = { workspace = true }

[[bin]]
name = "randomized-tests"
path = "src/main.rs"
bench = false
