[package]
name = "monad-randomized-tests"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[[bin]]
name = "monad-randomized-tests"
bench = false

[dependencies]
monad-chain-config = { workspace = true }
monad-consensus-types = { workspace = true }
monad-crypto = { workspace = true }
monad-eth-types = { path = "../monad-eth-types" }
monad-mock-swarm = { workspace = true }
monad-router-scheduler = { workspace = true }
monad-state-backend = { workspace = true }
monad-testutil = { workspace = true }
monad-transformer = { workspace = true }
monad-types = { workspace = true }
monad-updaters = { workspace = true }
monad-validator = { workspace = true }

inventory = { workspace = true }
simple-xml-builder = { workspace = true }
