[package]
name = "monad-eth-txpool"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
monad-consensus-types = { path = "../monad-consensus-types" }
monad-crypto = { path = "../monad-crypto" }
monad-eth-block-policy = { path = "../monad-eth-block-policy" }
monad-eth-tx = { path = "../monad-eth-tx" }
monad-eth-types = { path = "../monad-eth-types" }
monad-state-backend = { path = "../monad-state-backend" }
monad-types = { path = "../monad-types" }

alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
bytes = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
monad-crypto = { path = "../monad-crypto" }
monad-eth-testutil = { path = "../monad-eth-testutil" }
monad-perf-util = { path = "../monad-perf-util" }
monad-testutil = { path = "../monad-testutil" }
monad-types = { path = "../monad-types" }

alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
tracing-test = { workspace = true }

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "create_proposal"
harness = false

[[bench]]
name = "clear"
harness = false

