[state_root]
state_root_hash = "0x3aeacb8c741724594aa4d8853e431eb8378cf490cf27fc2f176ce02e93a61eb4"
seq_num = "0"

[root_qc]
signatures = "0x0a3ca4656f72646572736269747665633a3a6f726465723a3a4c7362306468656164a2657769647468184065696e6465780064626974730064646174618012c001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
signature_hash = "0x0fb1346d3fd54a316e2b16d74be47c4d285c15e1d406fc9c1e2126448c51397a"

[root_qc.info.vote]
ledger_commit_info = "NoCommit"

[root_qc.info.vote.vote_info]
id = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
epoch = 1
round = 0
parent_id = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
parent_round = 0
seq_num = "0"

[[validator_sets]]
epoch = 1
round = 0

[[validator_sets.validators]]
node_id = "0x02093852f554d6196025b0bebe21ea646f73e34f1fd6f154e6ae77c890363ea5be"
stake = 1
cert_pubkey = "0xab1011a17be0921c122fc7362f6e0401f80623c644bb9d9e9eedff0410a4de2259f0d3a36414d4dd9dd748ace56ffb5e"

[[validator_sets]]
epoch = 2

[[validator_sets.validators]]
node_id = "0x02093852f554d6196025b0bebe21ea646f73e34f1fd6f154e6ae77c890363ea5be"
stake = 1
cert_pubkey = "0xab1011a17be0921c122fc7362f6e0401f80623c644bb9d9e9eedff0410a4de2259f0d3a36414d4dd9dd748ace56ffb5e"
