#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

#########################################################
# Node-specific configuration
#########################################################
beneficiary = "0x0000000000000000000000000000000000000000"
node_name = "dev-node"
network_name = "devnet"
ipc_tx_batch_size = 500
ipc_max_queued_batches = 6
# must be <= ipc_max_queued_batches
ipc_queued_batches_watermark = 3

statesync_threshold = 600
statesync_max_concurrent_requests = 5

#########################################################
# Network-wide configuration
#########################################################
chain_id = 20143

#########################################################
# Node-specific configuration
#########################################################
raptor10_validator_redundancy_factor = 3

[bootstrap]
peers = []
# [[bootstrap.peers]]
# address = "x.x.x.x:xxxx"
# record_seq_num = 0
# secp256k1_pubkey = "..."
# name_record_sig = "..."

[peer_discovery]
self_address = "0.0.0.0:8000"
self_record_seq_num = 0
self_name_record_sig = "85663053b3d719985357b56270ba320abadd1c51e10ea06430f3990d81393dc7770ff661c331bd631afca705029b0fd77cc0f48d46b37c8d8523c73c6af1242801"
ping_period = 30
refresh_period = 120
request_timeout = 5
unresponsive_prune_threshold = 5
last_participation_prune_threshold = 5000
min_num_peers = 0
max_num_peers = 200

[fullnode_dedicated]
identities = []
# [[fullnode_dedicated.identities]]
# secp256k1_pubkey = "..."

[blocksync_override]
peers = []
# [[blocksync_override.peers]]
# secp256k1_pubkey = "..."

[statesync]
peers = []
# [[statesync.peers]]
# secp256k1_pubkey = "..."

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8000
max_rtt_ms = 300
max_mbps = 1000

#########################################################
# Network-wide configuration
#########################################################
[consensus]
execution_delay = 10
