name: Benchmark Regression Check

on:
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-24.04-32
    permissions:
      pull-requests: write
      contents: write
      packages: read
      actions: read

    steps:
      # Check out pull request branch
      - uses: actions/checkout@v3
        with:
          path: pr
      # Check out base branch
      - uses: actions/checkout@v3
        with:
          ref: master
          path: master

      # Run benchmark on master
      - name: Run benchmark on master
        shell: bash
        run: cd master && cargo bench -- --output-format bencher --save-baseline master | tee bench.txt

      # Copy baseline results to the PR directory so that criterion can properly recognize it as a baseline
      - name: Copy baseline results
        run: mkdir -p pr/target/criterion && cp -r master/target/criterion/* pr/target/criterion

      # Run benchmark on PR
      - name: Run benchmark on PR
        shell: bash
        run: cd pr && cargo bench -- --output-format bencher --baseline master | tee bench.txt

      - name: Compare benchmarks
        uses: openpgpjs/github-action-pull-request-benchmark@v1
        with:
          name: 'BenchmarkCompare'
          tool: 'cargo'
          pr-benchmark-file-path: pr/bench.txt
          base-benchmark-file-path: master/bench.txt
          comment-always: true
          fail-on-alert: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive criterion benchmark plots
        uses: actions/upload-artifact@v4
        with:
          name: criterion benchmark plot
          path: |
            pr/target/criterion
