name: Create and publish a Docker image

on:
  push:
    branches:
      - 'release*'
      - 'staging*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-monad-bft:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: docker/devnet/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-monad-full-node:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/monad-crypto/monad-full-node
          tags: |
            type=ref,event=branch
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: docker/devnet/fullnode.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-monad-rpc:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/monad-crypto/monad-rpc
          tags: |
            type=ref,event=branch
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: docker/rpc/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-monad-execution:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    env:
      MONAD_EXECUTION_ROOT: ${{ github.workspace }}/monad-cxx/monad-execution

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/monad-crypto/monad-execution
          tags: |
            type=ref,event=branch
            type=sha,prefix=

      - name: Setup Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
      
      - run: cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
      - run: cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
      - run: sudo bash -c "echo 2048 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages"
      - run: sudo bash -c "echo 8 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages"
      - run: cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
      - run: cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages

      - name: Get Execution Commit Hash
        run: echo "GIT_COMMIT_HASH=$(git -C ${{ env.MONAD_EXECUTION_ROOT }} rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ env.MONAD_EXECUTION_ROOT }}
          push: true
          file: ${{ env.MONAD_EXECUTION_ROOT }}/docker/release.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}
          builder: ${{ steps.setup-buildx.outputs.name }}
          allow: security.insecure

  publish-monad-tx-gen:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/monad-crypto/monad-tx-gen
          tags: |
            type=ref,event=branch
            type=sha,prefix=
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: docker/txgen/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  publish-monad-archive:
    runs-on: ubuntu-24.04-32

    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_READONLY_GITHUB_APP_ID }}
          private_key: ${{ secrets.REPO_READONLY_GITHUB_APP_KEY }}
          permissions: >-
            {"contents": "read"}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.generate_token.outputs.token }}

      - name: Log in to the Peach10 Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: peach10.devcore4.com
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            peach10.devcore4.com/monad-crypto/monad-archive
          tags: |
            type=ref,event=branch
            type=sha,prefix=
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          file: docker/archive/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}